### ISSUE TITLE
验证码识别出错，响应内容以json格式解析失败

### ISSUE THREAD

**Issue by LiarOnce** [IceTiki/ruoli-sign-optimization#109]
部分日志：
```
[验证码处理失败, 错误信息: 
『响应内容以json格式解析失败(Expecting value: line 1 column 1 (char 0))，响应内容:

Method Not Allowed』]
Traceback (most recent call last):
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/handler.py", line 72, in execute
    self._execute()
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/handler.py", line 152, in _execute
    msg = sign.submitForm()
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/actions/autoSign.py", line 305, in submitForm
    self.getSubmitExtension()
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/actions/autoSign.py", line 266, in getSubmitExtension
    self.form.update(CpdailyTools.handleCaptcha(
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/liteTools.py", line 518, in handleCaptcha
    raise Exception(f"验证码处理失败, 错误信息: \n『{error}』")
Exception: 验证码处理失败, 错误信息: 
『响应内容以json格式解析失败(Expecting value: line 1 column 1 (char 0))，响应内容:

Method Not Allowed』
```

**Comment by IceTiki** [comment]
我猜你找错了苹果，如果你找到了，应该会看到 恭喜你找到了苹果

**Comment by LiarOnce** [comment]
这个也是找错了的吧：
```
[验证码处理失败, 错误信息: 
『'NoneType' object is not subscriptable』]
Traceback (most recent call last):
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/handler.py", line 72, in execute
    self._execute()
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/handler.py", line 152, in _execute
    msg = sign.submitForm()
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/actions/autoSign.py", line 305, in submitForm
    self.getSubmitExtension()
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/actions/autoSign.py", line 266, in getSubmitExtension
    self.form.update(CpdailyTools.handleCaptcha(
  File "/home/liaronce/autoscripts/ruoli-sign-optimization/liteTools.py", line 518, in handleCaptcha
    raise Exception(f"验证码处理失败, 错误信息: \n『{error}』")
Exception: 验证码处理失败, 错误信息: 
『'NoneType' object is not subscriptable』
```
