### ISSUE TITLE
这个能否脚本能否在本地运行

### ISSUE THREAD

**Issue by 5i03** [IceTiki/ruoli-sign-optimization#11]
今天测试的时候发现云函数上海已经不行了,只剩一个北京还能正常用,不知北京后续会不会被禁用,所以请教一下,能否在本地运行.谢谢

**Comment by IceTiki** [comment]
可以

**Comment by 5i03** [comment]
我在本地运行，需要指定入口吗

**Comment by 5i03** [comment]
直接运行似乎会报错

**Comment by 5i03** [comment]
报错日志
```
Traceback (most recent call last):
  File "/Users/cnyue/Downloads/helloworld-1642179449/src/index.py", line 3, in <module>
    from todayLoginService import TodayLoginService
  File "/Users/cnyue/Downloads/helloworld-1642179449/src/todayLoginService.py", line 7, in <module>
    from login.Utils import Utils
  File "/Users/cnyue/Downloads/helloworld-1642179449/src/login/Utils.py", line 9, in <module>
    from Crypto.Cipher import AES
  File "/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Cipher/_mode_ecb.py", line 47, in <module>
    """
  File "/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/_raw_api.py", line 297, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-36m-darwin.so': cannot load library '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.cpython-36m-darwin.so': dlopen(/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.cpython-36m-darwin.so, 0x0002): tried: '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.cpython-36m-darwin.so' (no such file), '/usr/local/lib/_raw_ecb.cpython-36m-darwin.so' (no such file), '/usr/lib/_raw_ecb.cpython-36m-darwin.so' (no such file), '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Cipher/_raw_ecb.cpython-36m-darwin.so' (no such file), '/usr/local/lib/_raw_ecb.cpython-36m-darwin.so' (no such file), '/usr/lib/_raw_ecb.cpython-36m-darwin.so' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.cpython-36m-darwin.so', Trying '_raw_ecb.abi3.so': cannot load library '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.abi3.so': dlopen(/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 0x0002): tried: '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.abi3.so' (not a mach-o file), '/usr/local/lib/_raw_ecb.abi3.so' (no such file), '/usr/lib/_raw_ecb.abi3.so' (no such file), '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Cipher/_raw_ecb.abi3.so' (not a mach-o file), '/usr/local/lib/_raw_ecb.abi3.so' (no such file), '/usr/lib/_raw_ecb.abi3.so' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.abi3.so', Trying '_raw_ecb.so': cannot load library '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.so': dlopen(/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.so, 0x0002): tried: '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.so' (no such file), '/usr/local/lib/_raw_ecb.so' (no such file), '/usr/lib/_raw_ecb.so' (no such file), '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Cipher/_raw_ecb.so' (no such file), '/usr/local/lib/_raw_ecb.so' (no such file), '/usr/lib/_raw_ecb.so' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/cnyue/Downloads/helloworld-1642179449/src/Crypto/Util/../Cipher/_raw_ecb.so'

```

**Comment by IceTiki** [comment]
依赖版本有问题，你可能用了linux版本的依赖。
建议重新下代码重新安装依赖。(用pip intstall)

**Comment by IceTiki** [comment]
> 我在本地运行，需要指定入口吗

不需要，程序会自动找到入口进去。
