### ISSUE TITLE
验证码处理失败, 错误信息: 『'code'』

### ISSUE THREAD

**Issue by aiXlau** [IceTiki/ruoli-sign-optimization#110]
>>[验证码处理失败, 错误信息:
『'code'』]
Traceback (most recent call last):
File "/root/test/wuka/handler.py", line 72, in execute
self._execute()
File "/root/test/wuka/handler.py", line 152, in _execute
msg = sign.submitForm()
File "/root/test/wuka/actions/autoSign.py", line 305, in submitForm
self.getSubmitExtension()
File "/root/test/wuka/actions/autoSign.py", line 267, in getSubmitExtension
self.host, self.session, self.userInfo['deviceId']))
File "/root/test/wuka/liteTools.py", line 518, in handleCaptcha
raise Exception(f"验证码处理失败, 错误信息: \n『{error}』")
Exception: 验证码处理失败, 错误信息:
『'code'』

**Comment by IceTiki** [comment]
我猜你找错了苹果，如果你找到了，应该会看到 恭喜你找到了苹果
