### ISSUE TITLE
我们这个项目的OCR如何配置

### ISSUE THREAD

**Issue by ygk666** [IceTiki/ruoli-sign-optimization#114]

**Comment by IceTiki** [comment]
哪个OCR

**Comment by ygk666** [comment]
> 哪个OCR

配置文件里的ocr，腾讯的，那边要求填密钥，到时应该还要其他的地方

**Comment by ygk666** [comment]
还有，签到模块有bug，会明明有验证码他直接识别成无，null，最后呈现验签失败。查寝模块没出现

**Comment by ygk666** [comment]
> 还有，签到模块有bug，会明明有验证码他直接识别成无，null，最后呈现验签失败。查寝模块没出现

具体的你可以去问coderookieiv

**Comment by IceTiki** [comment]
> 还有，签到模块有bug，会明明有验证码他直接识别成无，null，最后呈现验签失败。查寝模块没出现

好了，这个bug修复了

**Comment by ygk666** [comment]
![image](https://user-images.githubusercontent.com/105439362/194802545-682bb089-b0d0-4c67-95ad-1fb4ea40b35a.png)

**Comment by ygk666** [comment]
早上六点会出现这个报错，请问是什么导致的

**Comment by IceTiki** [comment]
> 早上六点会出现这个报错，请问是什么导致的
> 

日志内容太少不确定，也可能是半夜你们学校服务器关了

**Comment by ygk666** [comment]
> > 早上六点会出现这个报错，请问是什么导致的
> 
> 日志内容太少不确定，也可能是半夜你们学校服务器关了
用户自定义函数执行出错, 错误信息『「HTTPConnectionPool(host='124.222.247.250', port=80): Read timed out. (read timeout=30)」

Traceback (most recent call last):

  File "/var/user/urllib3/connectionpool.py", line 445, in _make_request

    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "/var/user/urllib3/connectionpool.py", line 440, in _make_request

    httplib_response = conn.getresponse()

  File "/var/lang/python37/lib/python3.7/http/client.py", line 1373, in getresponse

    response.begin()

  File "/var/lang/python37/lib/python3.7/http/client.py", line 319, in begin

    version, status, reason = self._read_status()

  File "/var/lang/python37/lib/python3.7/http/client.py", line 280, in _read_status

    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "/var/lang/python37/lib/python3.7/socket.py", line 589, in readinto

    return self._sock.recv_into(b)

socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/user/requests/adapters.py", line 449, in send

    timeout=timeout

  File "/var/user/urllib3/connectionpool.py", line 756, in urlopen

    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "/var/user/urllib3/util/retry.py", line 532, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "/var/user/urllib3/packages/six.py", line 770, in reraise

    raise value

  File "/var/user/urllib3/connectionpool.py", line 706, in urlopen

    chunked=chunked,

  File "/var/user/urllib3/connectionpool.py", line 447, in _make_request

    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)

  File "/var/user/urllib3/connectionpool.py", line 337, in _raise_timeout

    self, url, "Read timed out. (read timeout=%s)" % timeout_value

urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='124.222.247.250', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/user/liteTools.py", line 1143, in trigger

    result["result"] = cla._userIndex(event, context)

  File "/var/user/userDefined.py", line 62, in index

    return event.execute()

  File "/var/user/userDefined.py", line 11, in execute

    return self.handleCapcha()

  File "/var/user/userDefined.py", line 32, in handleCapcha

    res = reqSession().post(apple, json=capCode)

  File "/var/user/requests/sessions.py", line 590, in post

    return self.request('POST', url, data=data, json=json, **kwargs)

  File "/var/user/liteTools.py", line 46, in request

    res = super(reqSession, self).request(*args, **kwargs)

  File "/var/user/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/var/user/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/var/user/requests/adapters.py", line 529, in send

    raise ReadTimeout(e, request=request)

requests.exceptions.ReadTimeout: HTTPConnectionPool(host='124.222.247.250', port=80): Read timed out. (read timeout=30)

』

|||V-T3.11.0a-?|||error|||107.639s|||

验证码识别出错: HTTPConnectionPool(host='124.222.247.250', port=80): Read timed out. (read timeout=30)

|||V-T3.11.0a-?|||debug|||107.639s|||

程序正在暂停5.389秒

|||V-T3.11.0a-?|||error|||113.035s|||

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

[验证码处理失败, 错误信息: 

『HTTPConnectionPool(host='124.222.247.250', port=80): Read timed out. (read timeout=30)』]

Traceback (most recent call last):

  File "/var/user/handler.py", line 73, in execute

    self._execute()

  File "/var/user/handler.py", line 153, in _execute

    msg = sign.submitForm()

  File "/var/user/actions/autoSign.py", line 308, in submitForm

    self.getSubmitExtension()

  File "/var/user/actions/autoSign.py", line 271, in getSubmitExtension

    self.host, self.session, self.userInfo['deviceId']))

  File "/var/user/liteTools.py", line 519, in handleCaptcha

    raise Exception(f"验证码处理失败, 错误信息: \n『{error}』")

Exception: 验证码处理失败, 错误信息: 

『HTTPConnectionPool(host='124.222.247.250', port=80): Read timed out. (read timeout=30)』

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

**Comment by ygk666** [comment]
> > 早上六点会出现这个报错，请问是什么导致的
> 
> 日志内容太少不确定，也可能是半夜你们学校服务器关了

这是完整日志请过目

**Comment by IceTiki** [comment]
> > > 早上六点会出现这个报错，请问是什么导致的
> > 
> > 
> > 日志内容太少不确定，也可能是半夜你们学校服务器关了
> 
> 这是完整日志请过目

如果只有六点不行，多半是六点的时候你学校服务器没开，你六点的时候手动登录办事大厅/教务系统试试就知道了

**Comment by IceTiki** [comment]
我知道问题在哪里了。你的apple似乎用的是旧版。你提供一下qq吧
