### ISSUE TITLE
云函数运行出现这个

### ISSUE THREAD

**Issue by ACSDSZ** [IceTiki/ruoli-sign-optimization#115]
||V-T3.11.0e|||info|||380.396s|||

正在进行第1次验证码识别尝试

http://1*******99 "POST http://********e.net/captcha-open-api/v1/captcha/create/scenesImage HTTP/1.1" 307 180

|||V-T3.11.0e|||error|||410.567s|||

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

[HTTPSConnectionPool(host='*******', port=443): Read timed out. (read timeout=30)]

Traceback (most recent call last):

  File "/var/user/urllib3/connectionpool.py", line 445, in _make_request

    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "/var/user/urllib3/connectionpool.py", line 440, in _make_request

    httplib_response = conn.getresponse()

  File "/var/lang/python37/lib/python3.7/http/client.py", line 1373, in getresponse

    response.begin()

  File "/var/lang/python37/lib/python3.7/http/client.py", line 319, in begin

    version, status, reason = self._read_status()

  File "/var/lang/python37/lib/python3.7/http/client.py", line 280, in _read_status

    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "/var/lang/python37/lib/python3.7/socket.py", line 589, in readinto

    return self._sock.recv_into(b)

  File "/var/lang/python37/lib/python3.7/ssl.py", line 1071, in recv_into

    return self.read(nbytes, buffer)

  File "/var/lang/python37/lib/python3.7/ssl.py", line 929, in read

    return self._sslobj.read(len, buffer)

socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/user/requests/adapters.py", line 449, in send

    timeout=timeout

  File "/var/user/urllib3/connectionpool.py", line 756, in urlopen

    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "/var/user/urllib3/util/retry.py", line 532, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "/var/user/urllib3/packages/six.py", line 770, in reraise

    raise value

  File "/var/user/urllib3/connectionpool.py", line 706, in urlopen

    chunked=chunked,

  File "/var/user/urllib3/connectionpool.py", line 447, in _make_request

    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)

  File "/var/user/urllib3/connectionpool.py", line 337, in _raise_timeout

    self, url, "Read timed out. (read timeout=%s)" % timeout_value

urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='*****', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/user/handler.py", line 72, in execute

    self._execute()

  File "/var/user/handler.py", line 152, in _execute

    msg = sign.submitForm()

  File "/var/user/actions/autoSign.py", line 305, in submitForm

    self.getSubmitExtension()

  File "/var/user/actions/autoSign.py", line 267, in getSubmitExtension

    self.host, self.session, self.userInfo['deviceId'], signType="sign"))

  File "/var/user/liteTools.py", line 479, in handleCaptcha

    data, boundary="----WebKitFormBoundaryBlRdUZvbYBzP5FaF"), headers=headers)

  File "/var/user/requests/sessions.py", line 590, in post

    return self.request('POST', url, data=data, json=json, **kwargs)

  File "/var/user/liteTools.py", line 46, in request

    res = super(reqSession, self).request(*args, **kwargs)

  File "/var/user/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/var/user/requests/sessions.py", line 677, in send

    history = [resp for resp in gen]

  File "/var/user/requests/sessions.py", line 677, in <listcomp>

    history = [resp for resp in gen]

  File "/var/user/requests/sessions.py", line 245, in resolve_redirects

    **adapter_kwargs

  File "/var/user/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/var/user/requests/adapters.py", line 529, in send

    raise ReadTimeout(e, request=request)

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='*', port=443): Read timed out. (read timeout=30)

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
运行起来出现这个

**Comment by ygk666** [comment]
我也是有时候有

**Comment by harvey9807** [comment]
代理问题吧

**Comment by ACSDSZ** [comment]
> 代理问题吧

在没有验证码之前都正常 用更新了图片验证码之后的就成这样了

**Comment by ACSDSZ** [comment]
> 代理问题吧

代理用的推荐的哪个

**Comment by ygk666** [comment]
> 代理问题吧

不是代理问题，我测试过用代理和不用都一样

**Comment by IceTiki** [comment]
似乎是有些学校生成二维码的接口不一样。目前在等待有这种问题的同学自己抓包找到问题。

**Comment by ACSDSZ** [comment]
> 似乎是有些学校生成二维码的接口不一样。目前在等待有这种问题的同学自己抓包找到问题。

这种要怎么搞 抓了看不懂
