### ISSUE TITLE
list index out of range怎么解决

### ISSUE THREAD

**Issue by bobpo2020** [IceTiki/ruoli-sign-optimization#12]
这个错误是啥原因，怎么解决

**Comment by bobpo2020** [comment]
Traceback (most recent call last):
  File "index.py", line 140, in main
    msg = working(user)
  File "index.py", line 66, in working
    today.login()
  File "C:\Users\Acer\Desktop\ruoli-sign-optimization-master\todayLoginService.py", line 92, in login
    self.checkLogin()
  File "C:\Users\Acer\Desktop\ruoli-sign-optimization-master\todayLoginService.py", line 86, in checkLogin
    self.session.cookies = self.loginEntity.login()
  File "C:\Users\Acer\Desktop\ruoli-sign-optimization-master\login\casLogin.py", line 40, in login
    soup = BeautifulSoup(str(form[1]), 'lxml')
IndexError: list index out of range

**Comment by IceTiki** [comment]
有些学校的教务系统有略微不同，所以登陆时抓取一个隐藏在页面的关键信息失败了。
登录组件我几乎没有改动过，也不是很熟悉，不一定懂怎么修复这个问题。（而且最近在忙课程设计，有时间再看看吧）

**Comment by bobpo2020** [comment]
> 

十分感谢回复

**Comment by IceTiki** [comment]
你们学校的教务系统的域名是什么，有时间我去看看。

**Comment by IceTiki** [comment]
> > 有些学校的教务系统有略微不同，所以登陆时抓取一个隐藏在页面的关键信息失败了。
> > 登录组件我几乎没有改动过，也不是很熟悉，不一定懂怎么修复这个问题。（而且最近在忙课程设计，有时间再看看吧）
> 
> 十分感谢回复

明天有更新会解决这个问题，你可以试试(现在还没更新)(2022-3-13--00-52-00)
