### ISSUE TITLE
indexError：list index out of range

### ISSUE THREAD

**Issue by dj00000000** [IceTiki/ruoli-sign-optimization#135]
direct_uri");
                if (redirect) {
                    document.getElementById("x_random")
                }
            </script>
</body>

</html>
|||V-T3.11.0i|||error|||7.704s|||
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[list index out of range]
Traceback (most recent call last):
  File "C:\Users\\Desktop\ruoli\handler.py", line 69, in execute
    self._beforeExecute()
  File "C:\Users\\Desktop\ruoli\handler.py", line 130, in _beforeExecute
    self._login()
  File "C:\Users\\Desktop\ruoli\handler.py", line 102, in _login
    today.login()
  File "C:\Users\\Desktop\ruoli\todayLoginService.py", line 104, in login
    self.checkLogin()
  File "C:\Users\\Desktop\ruoli\todayLoginService.py", line 98, in checkLogin
    self.session.cookies = self.loginEntity.login()
  File "C:\Users\\Desktop\ruoli\login\casLogin.py", line 132, in login
    msg = soup.select('#formErrorTip2')[0].get_text()
IndexError: list index out of range

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
签到失败[list index out of range]

**Comment by dj00000000** [comment]
这是啥问题啊

**Comment by IceTiki** [comment]
登陆失败，获取错误信息的时候出错了

**Comment by IceTiki** [comment]
这个问题只有在你登陆出错的时候才出现。
请手动登陆教务系统，检查是否需要更新密码更新手机号什么的，或者密码是否正确

**Comment by dj00000000** [comment]
我这账户和密码没有错误 刚才试了一下

**Comment by dj00000000** [comment]
有点小尴尬

**Comment by dj00000000** [comment]
![IMG_20221025_140245.jpg](https://user-images.githubusercontent.com/102505369/197694775-35e0a19f-fdd6-4210-9917-c412174e084f.jpg)

**Comment by IceTiki** [comment]
给下完整日志（.txt文件）

**Comment by dj00000000** [comment]
|||V-T3.11.0i|||info|||0.121s||| 一切代码文件保持初始状态 |||V-T3.11.0i|||info|||0.127s||| 正在初始化210530139的配置 |||V-T3.11.0i|||info|||0.130s||| 收到事件「任务序列即将执行(100)」, 尝试触发用户自定义函数 event code: 100 from: global start msg: 任务序列即将执行 context runTime: '2022-10-25 14:00:37' scriptVersion: V-T3.11.0i taskWebhook: - attempts: 0   maxtry: 1   msg: ''   remarkName: 默认备注名   scriptVersion: V-T3.11.0i   statusCode: 0   statusCodehead: 0   statusMsg: 等待执行   statusMsgLite: 待命   username: '210530139' taskcount_all: 1 taskcount_done: 0 taskcount_error: 0 taskcount_executed: 1 taskcount_notFound: 0 taskcount_skip: 0 taskcount_todo: 1 usedTime: 0.13 |||V-T3.11.0i|||info|||0.137s||| 用户自定义函数执行完毕, 返回值:  exceptError: null result: 什么都没有干 |||V-T3.11.0i|||info|||0.138s||| 任务开始执行 |||V-T3.11.0i|||info|||0.138s||| 正在进行第1轮尝试 |||V-T3.11.0i|||info|||0.138s||| 即将在第1轮尝试中为[210530139]签到 |||V-T3.11.0i|||debug|||0.138s||| 程序正在暂停0.991秒 |||V-T3.11.0i|||info|||1.144s||| 收到事件「『210530139』个人任务即将执行(200)」, 尝试触发用户自定义函数 event code: 200 from: task start msg: 『210530139』个人任务即将执行 context attempts: 1 maxtry: 1 msg: '' remarkName: 默认备注名 scriptVersion: V-T3.11.0i statusCode: 0 statusCodehead: 0 statusMsg: 等待执行 statusMsgLite: 待命 username: '210530139' |||V-T3.11.0i|||info|||1.145s||| 用户自定义函数执行完毕, 返回值:  exceptError: null result: 什么都没有干 |||V-T3.11.0i|||info|||1.145s||| 准备登录 |||V-T3.11.0i|||info|||1.145s||| 正在尝试进行登录 |||V-T3.11.0i|||info|||2.254s||| 「苏州市职业大学」接入今日校园方式为「NOTCLOUD」 |||V-T3.11.0i|||info|||2.969s||| 学校的教务系统登录地址为「https://authserver.jssvc.edu.cn/cas/login?service=https%3A%2F%2Fehall.jssvc.edu.cn%2Famp-auth-adapter%2FloginSuccess%3FsessionToken%3D0c9082853de2412584e3aa193e7da499」 <!DOCTYPE html &gt; <html style="height: 100%"&gt; <head&gt;     <meta charset="utf-8"&gt;     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"&gt;     <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" /&gt;     <title&gt;统一身份认证</title&gt;              <link href="/cas/resources/j6NaWquZYz/static/css/modules/login.310b35ca7e5afdf4326fee75505e0250.css?28494d5386a60641c8ae" rel="stylesheet"&gt;          </head&gt; <body&gt;     <div id="app"&gt;</div&gt;     <input id="x_random" type="hidden" value="" /&gt;     <input class="for-form" type="hidden" name="lt" value="LT-258257-2QWDpue1f5A3qgd2jdGpcmsbnRWKqq"&gt;     <input class="for-form" type="hidden" name="pid" value="homi1ii8" /&gt;     <span id="errorcode" class="for-form errorerror" value=""&gt;</span&gt;     <span id="errormes" class="for-form errorerror" value=""&gt;</span&gt;     <span id="errordetail" class="for-form errordetail" value=""&gt;</span&gt;     <input class="for-form" type="hidden" name="source" id="login-type" value="cas"&gt;     <input class="for-form" type="hidden" name="execution" value="e3s1"&gt;              <script type="text/javascript" src="/cas/resources/j6NaWquZYz/static/js/modules/login.043e9d12e8393b8a5aab.js?28494d5386a60641c8ae"&gt;</script&gt;                      <script type="text/javascript"&gt;                 function GetQueryString(name) {                     var reg = new RegExp("(^|&amp;)" + name + "=([^&amp;]*)(&amp;|$)");                     var r = window.location.search.substr(1).match(reg);                     if (r != null) return unescape(r[2]);                     return null;                 }                 var redirect = GetQueryString("redirect_uri");                 if (redirect) {                     document.getElementById("x_random")                 }             </script&gt; </body&gt; </html&gt; |||V-T3.11.0i|||error|||3.024s||| ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ [list index out of range] Traceback (most recent call last):   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 69, in execute     self._beforeExecute()   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 130, in _beforeExecute     self._login()   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 102, in _login     today.login()   File "C:\Users\邓菁\Desktop\ruoli\todayLoginService.py", line 104, in login     self.checkLogin()   File "C:\Users\邓菁\Desktop\ruoli\todayLoginService.py", line 98, in checkLogin     self.session.cookies = self.loginEntity.login()   File "C:\Users\邓菁\Desktop\ruoli\login\casLogin.py", line 132, in login     msg = soup.select('#formErrorTip2')[0].get_text() IndexError: list index out of range ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 210530139签到失败[list index out of range] Traceback (most recent call last):   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 69, in execute     self._beforeExecute()   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 130, in _beforeExecute     self._login()   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 102, in _login     today.login()   File "C:\Users\邓菁\Desktop\ruoli\todayLoginService.py", line 104, in login     self.checkLogin()   File "C:\Users\邓菁\Desktop\ruoli\todayLoginService.py", line 98, in checkLogin     self.session.cookies = self.loginEntity.login()   File "C:\Users\邓菁\Desktop\ruoli\login\casLogin.py", line 132, in login     msg = soup.select('#formErrorTip2')[0].get_text() IndexError: list index out of range |||V-T3.11.0i|||info|||3.026s||| 『用户签到情况(待命)[V-T3.11.0i]』 [默认备注名|210530139](1) &gt;&gt;[list index out of range] Traceback (most recent call last):   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 69, in execute     self._beforeExecute()   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 130, in _beforeExecute     self._login()   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 102, in _login     today.login()   File "C:\Users\邓菁\Desktop\ruoli\todayLoginService.py", line 104, in login     self.checkLogin()   File "C:\Users\邓菁\Desktop\ruoli\todayLoginService.py", line 98, in checkLogin     self.session.cookies = self.loginEntity.login()   File "C:\Users\邓菁\Desktop\ruoli\login\casLogin.py", line 132, in login     msg = soup.select('#formErrorTip2')[0].get_text() IndexError: list index out of range |||V-T3.11.0i|||info|||3.026s||| 『210530139』用户推送情况 推送情况 QMSG酱|无效配置 SMTP|无效配置 若离邮箱API|无效配置 IceCream|无效配置 Pushplus|无效配置 Serverchan|无效配置 Gotify|无效配置 |||V-T3.11.0i|||info|||3.028s||| 收到事件「『210530139』个人任务执行完成(201)」, 尝试触发用户自定义函数 event code: 201 from: task end msg: 『210530139』个人任务执行完成 context attempts: 1 maxtry: 1 msg: "[list index out of range]\nTraceback (most recent call last):\n  File \"C:\\\   Users\\邓菁\\Desktop\\ruoli\\handler.py\", line 69, in execute\n    self._beforeExecute()\n\   \  File \"C:\\Users\\邓菁\\Desktop\\ruoli\\handler.py\", line 130, in _beforeExecute\n\   \    self._login()\n  File \"C:\\Users\\邓菁\\Desktop\\ruoli\\handler.py\", line 102,\   \ in _login\n    today.login()\n  File \"C:\\Users\\邓菁\\Desktop\\ruoli\\todayLoginService.py\"\   , line 104, in login\n    self.checkLogin()\n  File \"C:\\Users\\邓菁\\Desktop\\ruoli\\\   todayLoginService.py\", line 98, in checkLogin\n    self.session.cookies = self.loginEntity.login()\n\   \  File \"C:\\Users\\邓菁\\Desktop\\ruoli\\login\\casLogin.py\", line 132, in login\n\   \    msg = soup.select('#formErrorTip2')[0].get_text()\nIndexError: list index out\   \ of range\n" remarkName: 默认备注名 scriptVersion: V-T3.11.0i statusCode: 1 statusCodehead: 0 statusMsg: 出现错误(等待重试) statusMsgLite: 待命 username: '210530139' |||V-T3.11.0i|||info|||3.029s||| 用户自定义函数执行完毕, 返回值:  exceptError: null result: 什么都没有干 |||V-T3.11.0i|||info|||3.030s||| 『全局签到情况(0/1)[V-T3.11.0i]』 [默认备注名|210530139](1) &gt;&gt;[list index out of range] Traceback (most recent call last):   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 69, in execute     self._beforeExecute()   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 130, in _beforeExecute     self._login()   File "C:\Users\邓菁\Desktop\ruoli\handler.py", line 102, in _login     today.login()   File "C:\Users\邓菁\Desktop\ruoli\todayLoginService.py", line 104, in login     self.checkLogin()   File "C:\Users\邓菁\Desktop\ruoli\todayLoginService.py", line 98, in checkLogin     self.session.cookies = self.loginEntity.login()   File "C:\Users\邓菁\Desktop\ruoli\login\casLogin.py", line 132, in login     msg = soup.select('#formErrorTip2')[0].get_text() IndexError: list index out of range 运行于2022-10-25 14:00:37, 用时3.03秒 1任务| 1待命, 0完成, 0跳过, 0错误, 0缺失




ddd
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IceTiki/ruoli-sign-optimization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IceTiki/ruoli-sign-optimization] indexError：list index out of range (Issue #135)





 
给下完整日志（.txt文件）

**Comment by Z2549** [comment]
我也是这样的情况一整天都是这样，在设备管理里删除所有设备也不行

**Comment by Z2549** [comment]
已经两天了，怎样测试都不行

**Comment by IceTiki** [comment]
这个问题暂时没找到原因（很迷）
