### ISSUE TITLE
『服务异常』验证码处理失败, 错误信息:HTTPSConnectionPool(host='', port=443)Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by vr-yan** [IceTiki/ruoli-sign-optimization#147]
>>[验证码处理失败, 错误信息:
『HTTPSConnectionPool(host='hello.world', port=443): Max retries exceeded with url: /hello.world (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))』]
Traceback (most recent call last):
File "/var/user/handler.py", line 72, in execute
self._execute()
File "/var/user/handler.py", line 152, in _execute
msg = sign.submitForm()
File "/var/user/actions/autoSign.py", line 305, in submitForm
self.getSubmitExtension()
File "/var/user/actions/autoSign.py", line 267, in getSubmitExtension
self.host, self.session, self.userInfo['deviceId']))
File "/var/user/liteTools.py", line 518, in handleCaptcha
raise Exception(f"验证码处理失败, 错误信息: \n『{error}』")
Exception: 验证码处理失败, 错误信息:
『HTTPSConnectionPool(host='hello.world', port=443): Max retries exceeded with url: /hello.world (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))』

**Comment by IceTiki** [comment]
验证码识别服务器上有误操作，正在修复，应该在近几天修复完成

**Comment by dozbamb** [comment]
> 验证码识别服务器上有误操作，正在修复，应该在近几天修复完成

>>[验证码处理失败, 错误信息:
『HTTPSConnectionPool(host='api.ruoli.cc', port=443): Max retries exceeded with url: /validate (Caused by SSLError(SSLCertVerificationError("hostname 'api.ruoli.cc' doesn't match 'apple.ruoli.cc'")))』]
Traceback (most recent call last):
File "/var/user/handler.py", line 71, in execute
self._execute()
File "/var/user/handler.py", line 143, in _execute
msg = collection.submitForm()
File "/var/user/actions/collection.py", line 436, in submitForm
self.getSubmitExtension()
File "/var/user/actions/collection.py", line 399, in getSubmitExtension
self.host, self.session, self.userInfo['deviceId'], signType="collector"))
File "/var/user/liteTools.py", line 525, in handleCaptcha
raise Exception(f"验证码处理失败, 错误信息: \n『{error}』")
Exception: 验证码处理失败, 错误信息:
『HTTPSConnectionPool(host='api.ruoli.cc', port=443): Max retries exceeded with url: /validate (Caused by SSLError(SSLCertVerificationError("hostname 'api.ruoli.cc' doesn't match 'apple.ruoli.cc'")))』
这是同一个问题吗

**Comment by IceTiki** [comment]
请重新打开文档页面重新填写，好像api地址换了

**Comment by dozbamb** [comment]
> 请重新打开文档页面重新填写，好像api地址换了

好的，谢谢了
