### ISSUE TITLE
腾讯云上传最新代码后，出现异常{"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", 

### ISSUE THREAD

**Issue by vr-yan** [IceTiki/ruoli-sign-optimization#158]
完整执行日志

START RequestId: 6251deb9-9596-4eeb-ab4f-83dcfab33edd

==========脚本开始初始化==========

Init Report RequestId: 6251deb9-9596-4eeb-ab4f-83dcfab33edd Coldstart: 1151ms (PullCode: 0ms InitRuntime: 3ms InitFunction: 1148ms) Memory: 128MB MemUsage: 24.30MB

ERROR RequestId: 6251deb9-9596-4eeb-ab4f-83dcfab33edd Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 92, in <module>     from handler import MainHandler   File "/var/user/handler.py", line 5, in <module>     from liteTools import UserDefined, LL, TT, DT, HSF, ST, RT, ProxyGet, TaskError   File "/var/user/liteTools.py", line 22, in <module>     import PIL.Image as PIL_Image   File "/var/user/PIL/Image.py", line 59, in <module>     from ._deprecate import deprecate   File "/var/user/PIL/_deprecate.py", line 1     from __future__ import annotations                                      ^ SyntaxError: future feature annotations is not defined", "statusCode": 443}

END RequestId: 6251deb9-9596-4eeb-ab4f-83dcfab33edd

Report RequestId: 6251deb9-9596-4eeb-ab4f-83dcfab33edd Duration: 0ms Memory: 128MB MemUsage: 24.30MB

**Comment by IceTiki** [comment]
似乎是pillow和python的版本不匹配...

**Comment by IceTiki** [comment]
你截图一下你的依赖文件夹看下

**Comment by vr-yan** [comment]
截图
https://s2.loli.net/2023/03/07/uveBLgs7VAIMoxd.png
https://s2.loli.net/2023/03/07/VutRnaYGwq5AoIH.png
之前旧版的在腾讯云可以正常跑，前天重新部署了最新的就不行 我还是用的3.6版本，那应该是版本问题

**Comment by IceTiki** [comment]
![image](https://user-images.githubusercontent.com/61530581/224222120-52043254-ec70-4167-a1b9-ebc9ec9b74e9.png)
你试试删掉pillow？反正腾讯云函数环境自带pillow
