### ISSUE TITLE
在部分环境下可能存在的字符串编码问题

### ISSUE THREAD

**Issue by 5i03** [IceTiki/ruoli-sign-optimization#18]
报错日志如下:
```
Traceback (most recent call last):
  File "index.py", line 241, in <module>
    main()
  File "index.py", line 181, in main
    config = loadConfig()
  File "index.py", line 75, in loadConfig
    LL.log(1, f"\u6b63\u5728\u521d\u59cb\u5316{user['username']}\u7684\u914d\u7f6e")
  File "/usr/local/var/functions/ap-chengdu/lam-ragaxi77/helloworld-1644216336/src/liteTools.py", line 278, in log
    print(LL.log2FormatStr(logItem))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-35: ordinal not in range(128)
```
我的处理:改变标准输出的默认编码,问题得到了缓解
```
import sys,io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
#设置默认输出编码为utf-8
```

如果这是个问题,烦请作者大大修复,谢谢!

**Comment by IceTiki** [comment]
因为```sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")```似乎在运行结束时才输出结果
所以我改用```sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())```

**Comment by 5i03** [comment]
对,编码utf-8就行

**Comment by 5i03** [comment]
我测试时候发现编码问题是在输出段
