### ISSUE TITLE
模块路径不同系统采用不同写法不同导致的报错

### ISSUE THREAD

**Issue by 5i03** [IceTiki/ruoli-sign-optimization#19]
执行日志如下:
```
!!!!!!!!!!!!!!脚本代码文件缺失!!!!!!!!!!!!!!
请尝试重新下载代码
错误信息: No module named 'actions\\autoSign'
Traceback (most recent call last):
  File "index.py", line 42, in <module>
    raise e
  File "index.py", line 35, in <module>
    imp.find_module(i)
  File "/var/lang/python3/lib/python3.6/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'actions\\autoSign'
```
我的处理:
```
头部增加
import platform
```
我的处理:修改 检查代码完整性部分,在其这增加一个系统判断,问题得到缓解
```
try:
    if platform.system().lower() == 'windows':
        print("检查代码完整性Windows")
        for i in ("todayLoginService", "actions\\autoSign", "actions\\collection", "actions\\sleepCheck", "actions\\workLog", "actions\\sendMessage", "actions\\teacherSign", "login\\Utils", "login\\casLogin", "login\\iapLogin", "login\\RSALogin", "liteTools"):
            imp.find_module(i)
    elif platform.system().lower() == 'linux':
        print("代码完整性检查linux")
        for i in ("todayLoginService", "actions/autoSign", "actions/collection", "actions/sleepCheck", "actions/workLog", "actions/sendMessage", "actions/teacherSign", "login/Utils", "login/casLogin", "login/iapLogin", "login/RSALogin", "liteTools"):
            imp.find_module(i)         
    elif platform.system().lower() == 'darwin':
        print("代码完整性检查osx")
        for i in ("todayLoginService", "actions/autoSign", "actions/collection", "actions/sleepCheck", "actions/workLog", "actions/sendMessage", "actions/teacherSign", "login/Utils", "login/casLogin", "login/iapLogin", "login/RSALogin", "liteTools"):
            imp.find_module(i)       
    else:
        print("不支持当前的操作系统:{}".format(platform.system().lower()))
    #5i03: Darwin就是苹果的macOS/OS X 加了一个判断
    # for i in ("todayLoginService", "actions\\autoSign", "actions\\collection", "actions\\sleepCheck", "actions\\workLog", "actions\\sendMessage", "actions\\teacherSign", "login\\Utils", "login\\casLogin", "login\\iapLogin", "login\\RSALogin", "liteTools"):
    #       imp.find_module(i) 
    # for i in ("todayLoginService", "actions/autoSign", "actions/collection", "actions/sleepCheck", "actions/workLog", "actions/sendMessage", "actions/teacherSign", "login/Utils", "login/casLogin", "login/iapLogin", "login/RSALogin", "liteTools"):
    #     imp.find_module(i)
except ImportError as e:
    print(f"""!!!!!!!!!!!!!!脚本代码文件缺失!!!!!!!!!!!!!!
请尝试重新下载代码
错误信息: {e}""")
    raise e
```
如果这是一个问题,望作者大大修复,谢谢!

**Comment by IceTiki** [comment]
用```os.path.normpath()```适配了不同系统环境(这个函数会根据系统标准化路径)

**Comment by 5i03** [comment]
因为我在云函数执行的时候,会报这里出错,所以我执行了这个修改,问题得到缓解

**Comment by YYplus** [comment]
> 用`os.path.normpath()`不同的系统环境（这个函数会根据系统不同的路径）

今天用云函数部署的还是存在这个问题

**Comment by IceTiki** [comment]
> > 用`os.path.normpath()`不同的系统环境（这个函数会根据系统不同的路径）
> 
> 今天用云函数部署的还是存在这个问题

啊，修了，原来linux的os.path.normpath不会吧\转为/

**Comment by 5i03** [comment]
今天凌晨两点我拉了最新的代码测试,发现报错依旧,我还正想和你说嘞😂<br>
