### ISSUE TITLE
信息收集填写失败

### ISSUE THREAD

**Issue by 15037585178** [IceTiki/ruoli-sign-optimization#22]
签到失败Invalid URL '': No schema supplied. Perhaps you meant http://?
|||V-T3.4.0|||info|||6.739s|||

**Comment by IceTiki** [comment]
日志截得太少了

**Comment by 15037585178** [comment]
|||V-T3.4.0|||info|||1.505s|||
正在初始化1902016134的配置
|||V-T3.4.0|||info|||1.506s|||
正在进行第1轮尝试
|||V-T3.4.0|||info|||1.506s|||
即将在第1轮尝试中为[1902016134]签到
|||V-T3.4.0|||debug|||1.506s|||
程序正在暂停5.479秒
|||V-T3.4.0|||info|||6.991s|||
准备登录
|||V-T3.4.0|||error|||7.539s|||
Traceback (most recent call last):
  File "D:/暴风影音/新建文件夹 (3)/ruoli-sign-optimization-master/index.py", line 193, in main
    msg = working(user)
  File "D:/暴风影音/新建文件夹 (3)/ruoli-sign-optimization-master/index.py", line 118, in working
    today.login()
  File "D:\暴风影音\新建文件夹 (3)\ruoli-sign-optimization-master\todayLoginService.py", line 92, in login
    self.checkLogin()
  File "D:\暴风影音\新建文件夹 (3)\ruoli-sign-optimization-master\todayLoginService.py", line 86, in checkLogin
    self.session.cookies = self.loginEntity.login()
  File "D:\暴风影音\新建文件夹 (3)\ruoli-sign-optimization-master\login\casLogin.py", line 33, in login
    html = self.session.get(self.login_url, verify=False).text
  File "D:\暴风影音\新建文件夹 (3)\ruoli-sign-optimization-master\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\暴风影音\新建文件夹 (3)\ruoli-sign-optimization-master\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "D:\暴风影音\新建文件夹 (3)\ruoli-sign-optimization-master\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "D:\暴风影音\新建文件夹 (3)\ruoli-sign-optimization-master\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "D:\暴风影音\新建文件夹 (3)\ruoli-sign-optimization-master\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

1902016134签到失败Invalid URL '': No schema supplied. Perhaps you meant http://?
|||V-T3.4.0|||info|||7.540s|||
--1902016134|1
--Invalid URL '': No schema supplied. Perhaps you meant http://?
|||V-T3.4.0|||info|||7.540s|||
推送情况

Qmsg配置错误，信息取消发送
邮件配置出错
邮箱或邮件api填写无效，已取消发送邮件！
pushplus的令牌填写错误，已取消发送！
|||V-T3.4.0|||info|||7.540s|||
==签到情况==
[默认备注名]
--1902016134|1
--Invalid URL '': No schema supplied. Perhaps you meant http://?

|||V-T3.4.0|||info|||7.540s|||
推送情况

Qmsg配置错误，信息取消发送
邮件配置出错
邮箱或邮件api填写无效，已取消发送邮件！
pushplus的令牌填写错误，已取消发送！

**Comment by IceTiki** [comment]
你们学校名称是什么

**Comment by 15037585178** [comment]
> 你们学校的名字是什么

https://hbzy.campusphere.net/wec-counselor-collector-apps/stu/mobile/index.html?collectorWid=14707&from=push&instanceWid=6666

**Comment by 15037585178** [comment]
> 你们学校的名字是什么

鹤壁职业技术学院

**Comment by 15037585178** [comment]
> 你们学校的名字是什么

作者大大 这个是我QQ 1035712030 有空能帮看下吗
