### ISSUE TITLE
签到失败('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

### ISSUE THREAD

**Issue by TheRainTime** [IceTiki/ruoli-sign-optimization#31]
签到失败了大佬！
而且上海节点被Ban了

|||V-T3.4.1|||debug|||46.408s|||

程序正在暂停8.502秒

|||V-T3.4.1|||info|||54.919s|||

准备登录

Starting new HTTPS connection (1): mobile.campushoy.com:443

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=fzu HTTP/1.1" 200 None

Starting new HTTPS connection (1): fzu.campusphere.net:443

https://fzu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178

https://fzu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154

https://fzu.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Ffzu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0

Starting new HTTP connection (1): id.fzu.edu.cn:80

http://id.fzu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Ffzu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Db0d1f3b496b1486fa54139146d88985f HTTP/1.1" 200 None

http://id.fzu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Ffzu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Db0d1f3b496b1486fa54139146d88985f HTTP/1.1" 200 None

|||V-T3.4.1|||error|||57.188s|||

Traceback (most recent call last):

  File "/var/user/urllib3/connectionpool.py", line 706, in urlopen

    chunked=chunked,

  File "/var/user/urllib3/connectionpool.py", line 445, in _make_request

    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "/var/user/urllib3/connectionpool.py", line 440, in _make_request

    httplib_response = conn.getresponse()

  File "/var/lang/python3/lib/python3.6/http/client.py", line 1331, in getresponse

    response.begin()

  File "/var/lang/python3/lib/python3.6/http/client.py", line 297, in begin

    version, status, reason = self._read_status()

  File "/var/lang/python3/lib/python3.6/http/client.py", line 266, in _read_status

    raise RemoteDisconnected("Remote end closed connection without"

http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/user/requests/adapters.py", line 449, in send

    timeout=timeout

  File "/var/user/urllib3/connectionpool.py", line 756, in urlopen

    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "/var/user/urllib3/util/retry.py", line 531, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "/var/user/urllib3/packages/six.py", line 734, in reraise

    raise value.with_traceback(tb)

  File "/var/user/urllib3/connectionpool.py", line 706, in urlopen

    chunked=chunked,

  File "/var/user/urllib3/connectionpool.py", line 445, in _make_request

    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "/var/user/urllib3/connectionpool.py", line 440, in _make_request

    httplib_response = conn.getresponse()

  File "/var/lang/python3/lib/python3.6/http/client.py", line 1331, in getresponse

    response.begin()

  File "/var/lang/python3/lib/python3.6/http/client.py", line 297, in begin

    version, status, reason = self._read_status()

  File "/var/lang/python3/lib/python3.6/http/client.py", line 266, in _read_status

    raise RemoteDisconnected("Remote end closed connection without"

urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/user/index.py", line 206, in main

    msg = working(user)

  File "/var/user/index.py", line 131, in working

    today.login()

  File "/var/user/todayLoginService.py", line 92, in login

    self.checkLogin()

  File "/var/user/todayLoginService.py", line 86, in checkLogin

    self.session.cookies = self.loginEntity.login()

  File "/var/user/login/casLogin.py", line 130, in login

    data = self.session.post(self.login_url, params=params, allow_redirects=False)

  File "/var/user/requests/sessions.py", line 590, in post

    return self.request('POST', url, data=data, json=json, **kwargs)

  File "/var/user/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/var/user/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/var/user/requests/adapters.py", line 498, in send

    raise ConnectionError(err, request=request)

requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

签到失败('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

|||V-T3.4.1|||info|||57.189s|||

**Comment by IceTiki** [comment]
试着填入可用的代理(我这边用自己电脑签，我也不清楚代理从哪里搞xd)

**Comment by IceTiki** [comment]
不过一般换个时间签到这个问题就解决了，有可能是太多人同时用的问题
