### ISSUE TITLE
无回复：教务系统出现了问题啦

### ISSUE THREAD

**Issue by q1226189767** [IceTiki/ruoli-sign-optimization#37]
--教务系统出现了问题啦！返回状态码：400   这是教务处禁用了吗

**Comment by IceTiki** [comment]
不确定，发下你教务系统的网址过来

**Comment by IceTiki** [comment]
还有，日志给全一点

**Comment by q1226189767** [comment]
[教务系统出现了问题啦！返回状态码：400]
Traceback (most recent call last):
  File "c:\Users\Owen\Desktop\ruoli-sign-optimization-master\index.py", line 202, in main
    msg = working(user)
  File "c:\Users\Owen\Desktop\ruoli-sign-optimization-master\index.py", line 126, in working
    today.login()
  File "c:\Users\Owen\Desktop\ruoli-sign-optimization-master\todayLoginService.py", line 92, in login     
    self.checkLogin()
  File "c:\Users\Owen\Desktop\ruoli-sign-optimization-master\todayLoginService.py", line 86, in checkLogin
    self.session.cookies = self.loginEntity.login()
  File "c:\Users\Owen\Desktop\ruoli-sign-optimization-master\login\casLogin.py", line 171, in login       
    raise Exception('教务系统出现了问题啦！返回状态码：' + str(data.status_code))
Exception: 教务系统出现了问题啦！返回状态码：400
