### ISSUE TITLE
教务网站报错

### ISSUE THREAD

**Issue by afterlif** [IceTiki/ruoli-sign-optimization#70]
用了很长时间没有问题然后学校说要换教务系统不知道是不是这个问题麻烦帮忙看看 
换过人少的时间点也不行

[HTTPConnectionPool(host='authserver.wspc.edu.cn', port=80): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fwspc.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D340ad6d118b34d2cb7b0b5c9083d62b5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6456c54b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))]
Traceback (most recent call last):
  File "/var/user/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/var/user/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/var/lang/python37/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/user/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/var/user/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/var/user/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/var/lang/python37/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/var/lang/python37/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/var/lang/python37/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/python37/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/var/lang/python37/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/var/user/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/var/user/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6456c54b90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/user/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/var/user/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/var/user/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='authserver.wspc.edu.cn', port=80): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fwspc.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D340ad6d118b34d2cb7b0b5c9083d62b5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6456c54b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/user/index.py", line 272, in main
    today.login()
  File "/var/user/todayLoginService.py", line 93, in login
    self.getLoginUrlBySchoolName()
  File "/var/user/todayLoginService.py", line 74, in getLoginUrlBySchoolName
    ampUrl2 = self.session.get(ampUrl2, verify=False).url
  File "/var/user/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/var/user/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/user/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/var/user/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/var/user/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/var/user/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/var/user/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='authserver.wspc.edu.cn', port=80): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fwspc.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D340ad6d118b34d2cb7b0b5c9083d62b5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6456c54b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by julynet** [comment]
+1 相同问题

**Comment by IceTiki** [comment]
手动点开了一下 http://authserver.wspc.edu.cn/
发现你们的教务系统还没有部署好。所以没办法从教务系统登录，目前来说没有解决方案，只能手签，或者等你们教务系统恢复了再尝试。

**Comment by julynet** [comment]
> 手动点开了一下 http://authserver.wspc.edu.cn/ 发现你们的教务系统还没有部署好。所以没办法从教务系统登录，目前来说没有解决方案，只能手签，或者等你们教务系统恢复了再尝试。

--[HTTPConnectionPool(host='id.hqu.edu.cn', port=80): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fhqu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D9be69684d92d44509b5e9c085723038c (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))]
Traceback (most recent call last):
File "/root/dk/urllib3/connection.py", line 170, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw
File "/root/dk/urllib3/util/connection.py", line 73, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/local/python3/lib/python3.7/socket.py", line 752, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/dk/urllib3/connectionpool.py", line 706, in urlopen
chunked=chunked,
File "/root/dk/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/root/dk/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/python3/lib/python3.7/http/client.py", line 1277, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/python3/lib/python3.7/http/client.py", line 1323, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/python3/lib/python3.7/http/client.py", line 1272, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/python3/lib/python3.7/http/client.py", line 1032, in _send_output
self.send(msg)
File "/usr/local/python3/lib/python3.7/http/client.py", line 972, in send
self.connect()
File "/root/dk/urllib3/connection.py", line 200, in connect
conn = self._new_conn()
File "/root/dk/urllib3/connection.py", line 182, in _new_conn
self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/dk/requests/adapters.py", line 449, in send
timeout=timeout
File "/root/dk/urllib3/connectionpool.py", line 756, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/root/dk/urllib3/util/retry.py", line 574, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='id.hqu.edu.cn', port=80): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fhqu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D9be69684d92d44509b5e9c085723038c (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "index.py", line 277, in main
today.login()
File "/root/dk/todayLoginService.py", line 93, in login
self.getLoginUrlBySchoolName()
File "/root/dk/todayLoginService.py", line 74, in getLoginUrlBySchoolName
ampUrl2 = self.session.get(ampUrl2, verify=False).url
File "/root/dk/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/root/dk/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/root/dk/requests/sessions.py", line 677, in send
history = [resp for resp in gen]
File "/root/dk/requests/sessions.py", line 677, in
history = [resp for resp in gen]
File "/root/dk/requests/sessions.py", line 245, in resolve_redirects
**adapter_kwargs
File "/root/dk/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/root/dk/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='id.hqu.edu.cn', port=80): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fhqu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D9be69684d92d44509b5e9c085723038c (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))
我的日志是这样的 最近几天有几率报错 并且我试了下host='id.hqu.edu.cn', port=80 一直都是可以访问的

**Comment by IceTiki** [comment]
可能是学校的服务器不稳定...从日志来看看不出脚本出现问题，你可以试试调多几次重试次数(在config.yml)
