### ISSUE TITLE
[教务系统出现了问题啦！返回状态码：502

### ISSUE THREAD

**Issue by he1215894612** [IceTiki/ruoli-sign-optimization#81]
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[教务系统出现了问题啦！返回状态码：502]
Traceback (most recent call last):
  File "g:\g\ruoli-sign-optimization-master\index.py", line 261, in main
    today.login()
  File "g:\g\ruoli-sign-optimization-master\todayLoginService.py", line 102, in login
    self.checkLogin()
  File "g:\g\ruoli-sign-optimization-master\todayLoginService.py", line 96, in checkLogin       
    self.session.cookies = self.loginEntity.login()
  File "g:\g\ruoli-sign-optimization-master\login\casLogin.py", line 135, in login
    raise Exception('教务系统出现了问题啦！返回状态码：' + str(data.status_code))
Exception: 教务系统出现了问题啦！返回状态码：502

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
091900409签到失败[教务系统出现了问题啦！返回状态码：502]
Traceback (most recent call last):
  File "g:\g\ruoli-sign-optimization-master\index.py", line 261, in main
    today.login()
  File "g:\g\ruoli-sign-optimization-master\todayLoginService.py", line 102, in login
    self.checkLogin()
  File "g:\g\ruoli-sign-optimization-master\todayLoginService.py", line 96, in checkLogin       
    self.session.cookies = self.loginEntity.login()
  File "g:\g\ruoli-sign-optimization-master\login\casLogin.py", line 135, in login
    raise Exception('教务系统出现了问题啦！返回状态码：' + str(data.status_code))
Exception: 教务系统出现了问题啦！返回状态码：502

|||V-T3.9.0d|||info|||38.847s|||
--091900409|1
--[教务系统出现了问题啦！返回状态码：502]
Traceback (most recent call last):
  File "g:\g\ruoli-sign-optimization-master\index.py", line 261, in main
    today.login()
  File "g:\g\ruoli-sign-optimization-master\todayLoginService.py", line 102, in login
    self.checkLogin()
  File "g:\g\ruoli-sign-optimization-master\todayLoginService.py", line 96, in checkLogin       
    self.session.cookies = self.loginEntity.login()
  File "g:\g\ruoli-sign-optimization-master\login\casLogin.py", line 135, in login
    raise Exception('教务系统出现了问题啦！返回状态码：' + str(data.status_code))
Exception: 教务系统出现了问题啦！返回状态码：502

**Comment by he1215894612** [comment]
在已经通过熊猫代理执行脚本的情况下，教务处还是不能登录。请问有可能使用手机号进行登录吗，直接绕过教务处。我们学校的教务处好像问题一直很多。FZU。恳请作者大大答复，感谢。

**Comment by IceTiki** [comment]
目前来看不可能手机登陆(手机要短信验证码)
教务系统如果手登都很困难，那应该是没法自动签到了

**Comment by he1215894612** [comment]
好的，感谢您的回复。zimo大佬的通用脚本中有手机号登录的代码，我自己捣鼓试试。

**Comment by IceTiki** [comment]
> 好的，感谢您的回复。zimo大佬的通用脚本中有手机号登录的代码，我自己捣鼓试试。

今日校园登陆方式只有
* 教务系统登陆(一般登陆模式)
* 短信验证码(这个需要想办法自动获取手机短信，很难实现)
* 微信/qq登陆(我不太清楚，不过比较少人用这个实现)
* 抓包手动登陆并保存cookie(但有存活时间)

子墨的仓库是很久远的仓库，有很多地方失修。里面手机号登陆很有可能只是用手机号作为账号在教务系统登陆(请注意分辨)。

目前能用的自动签到的登陆原理基本都是相同的(因为都是抄自若离的(包括本仓库))，若离的仓库是根据子墨改的。

所以，要么手签，要么尝试自己实现用其他方式登陆。
